In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.image import imread
import tensorflow as tf
import pandas as pd
import random
import cv2
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Select the Runtime > "Change runtime type" menu to enable a GPU accelerator, ')
  print('and then re-execute this cell.')
else:
  print(gpu_info)

Sat Nov 18 01:03:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
image_shape = (224,224,3)
batch_size = 32

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
image_gen = ImageDataGenerator()

In [ ]:
from keras.models import load_model

In [ ]:
def int_predict (pred_probabilities):
  predictions = np.zeros((pred_probabilities.shape[0],1),dtype=int)
  i = 0
  while i < pred_probabilities.shape[0]:
    predictions[i,:] = [np.argmax(pred_probabilities[i])]
    i = i + 1

  return predictions

In [ ]:
test_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/RXT teste nosso_data/'

#**PART 1**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/trein 2-3-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/1/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds nosso aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_nosso_data_part2345.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 177 images belonging to 4 classes.


In [ ]:
ac1v = model.evaluate(valid_image_gen)
ac1v

6/6 [==============================] - 74s 13s/step - loss: 0.9371 - accuracy: 0.8079


[0.9370558857917786, 0.8079096078872681]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

6/6 [==============================] - 1s 168ms/step


In [ ]:
classes1v = valid_image_gen.classes
#classes1v

In [ ]:
pred1v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[28,  3,  1,  0],
       [ 2, 39,  5,  6],
       [ 3,  5, 56,  1],
       [ 2,  5,  1, 20]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84        32
           1       0.75      0.75      0.75        52
           2       0.89      0.86      0.88        65
           3       0.74      0.71      0.73        28

    accuracy                           0.81       177
   macro avg       0.79      0.80      0.80       177
weighted avg       0.81      0.81      0.81       177



#**PART 2**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/trein 1-3-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/2/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds nosso aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_nosso_data_part1345.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 177 images belonging to 4 classes.


In [ ]:
ac2v = model.evaluate(valid_image_gen)
ac2v

6/6 [==============================] - 70s 14s/step - loss: 0.8555 - accuracy: 0.8588


[0.8555067777633667, 0.8587570786476135]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

6/6 [==============================] - 2s 231ms/step


In [ ]:
classes2v = valid_image_gen.classes
#classes1v

In [ ]:
pred2v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[29,  1,  1,  1],
       [ 2, 44,  4,  2],
       [ 2,  2, 60,  1],
       [ 1,  5,  3, 19]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88        32
           1       0.85      0.85      0.85        52
           2       0.88      0.92      0.90        65
           3       0.83      0.68      0.75        28

    accuracy                           0.86       177
   macro avg       0.85      0.84      0.84       177
weighted avg       0.86      0.86      0.86       177



#**PART 3**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/trein 1-2-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/3/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds nosso aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_nosso_data_part1245.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 177 images belonging to 4 classes.


In [ ]:
ac3v = model.evaluate(valid_image_gen)
ac3v

6/6 [==============================] - 72s 14s/step - loss: 0.7079 - accuracy: 0.8023


[0.7079415917396545, 0.8022598624229431]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

6/6 [==============================] - 1s 187ms/step


In [ ]:
classes3v = valid_image_gen.classes
#classes1v

In [ ]:
pred3v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[28,  1,  2,  1],
       [ 3, 39,  9,  1],
       [ 0,  0, 65,  0],
       [ 3,  5, 10, 10]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85        32
           1       0.87      0.75      0.80        52
           2       0.76      1.00      0.86        65
           3       0.83      0.36      0.50        28

    accuracy                           0.80       177
   macro avg       0.82      0.75      0.75       177
weighted avg       0.81      0.80      0.78       177



#**PART 4**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/trein 1-2-3-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/4/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds nosso aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_nosso_data_part1235.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 177 images belonging to 4 classes.


In [ ]:
ac4v = model.evaluate(valid_image_gen)
ac4v

6/6 [==============================] - 72s 14s/step - loss: 1.3534 - accuracy: 0.7797


[1.3533778190612793, 0.7796609997749329]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

6/6 [==============================] - 1s 185ms/step


In [ ]:
classes4v = valid_image_gen.classes
#classes1v

In [ ]:
pred4v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[28,  2,  2,  0],
       [ 1, 43,  6,  2],
       [ 4,  4, 54,  3],
       [ 5,  7,  3, 13]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.74      0.88      0.80        32
           1       0.77      0.83      0.80        52
           2       0.83      0.83      0.83        65
           3       0.72      0.46      0.57        28

    accuracy                           0.78       177
   macro avg       0.76      0.75      0.75       177
weighted avg       0.78      0.78      0.77       177



#**PART 5**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/trein 1-2-3-4/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds nosso_data aumentado/5/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds nosso aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_nosso_data_part1234.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 180 images belonging to 4 classes.


In [ ]:
ac5v = model.evaluate(valid_image_gen)
ac5v

6/6 [==============================] - 73s 15s/step - loss: 1.0275 - accuracy: 0.8222


[1.027510166168213, 0.8222222328186035]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

6/6 [==============================] - 1s 187ms/step


In [ ]:
classes5v = valid_image_gen.classes
#classes1v

In [ ]:
pred5v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[30,  2,  0,  1],
       [ 2, 40,  6,  6],
       [ 5,  3, 54,  3],
       [ 0,  3,  1, 24]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.81      0.91      0.86        33
           1       0.83      0.74      0.78        54
           2       0.89      0.83      0.86        65
           3       0.71      0.86      0.77        28

    accuracy                           0.82       180
   macro avg       0.81      0.83      0.82       180
weighted avg       0.83      0.82      0.82       180



#**Calculations**

VALIDATION

In [ ]:
acv_media = np.mean([ac1v[1],ac2v[1],ac3v[1],ac4v[1],ac5v[1]])
acv_media

0.8141619563102722

In [ ]:
todas_classesv = np.concatenate((classes1v,classes2v,classes3v,classes4v,classes5v),axis=0)

In [ ]:
todas_predv = np.concatenate((pred1v,pred2v,pred3v,pred4v,pred5v),axis=0)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

*   0: covid
*   1: dip
*   2: normais
*   3: tuberculose



In [ ]:
confusion_matrix(todas_classesv,todas_predv)

array([[143,   9,   6,   3],
       [ 10, 205,  30,  17],
       [ 14,  14, 289,   8],
       [ 11,  25,  18,  86]])

In [ ]:
print(classification_report(todas_classesv,todas_predv))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84       161
           1       0.81      0.78      0.80       262
           2       0.84      0.89      0.87       325
           3       0.75      0.61      0.68       140

    accuracy                           0.81       888
   macro avg       0.80      0.79      0.80       888
weighted avg       0.81      0.81      0.81       888



*   0: covid
*   1: dip
*   2: normais
*   3: tuberculose

