In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.image import imread
import tensorflow as tf
import pandas as pd
import random
import cv2
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Select the Runtime > "Change runtime type" menu to enable a GPU accelerator, ')
  print('and then re-execute this cell.')
else:
  print(gpu_info)

Sat Nov 18 16:31:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8    13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
image_shape = (224,224,3)
batch_size = 32

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
image_gen = ImageDataGenerator()

In [ ]:
from keras.models import load_model

In [ ]:
def int_predict (pred_probabilities):
  predictions = np.zeros((pred_probabilities.shape[0],1),dtype=int)
  i = 0
  while i < pred_probabilities.shape[0]:
    predictions[i,:] = [np.argmax(pred_probabilities[i])]
    i = i + 1

  return predictions

In [ ]:
test_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/RXT teste mix_data/'

#**PART 1**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/trein 2-3-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/1/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix/VGG19_fine-tuning_avg_4_classes_mix_data_part2345.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 337 images belonging to 4 classes.


In [ ]:
ac1v = model.evaluate(valid_image_gen)
ac1v

11/11 [==============================] - 242s 23s/step - loss: 0.6726 - accuracy: 0.8754


[0.672555148601532, 0.8753709197044373]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 2s 207ms/step


In [ ]:
classes1v = valid_image_gen.classes
#classes1v

In [ ]:
pred1v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[85,  4,  1,  5],
       [ 3, 42,  6,  1],
       [ 4,  1, 84,  6],
       [ 2,  6,  3, 84]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.90      0.89      0.90        95
           1       0.79      0.81      0.80        52
           2       0.89      0.88      0.89        95
           3       0.88      0.88      0.88        95

    accuracy                           0.88       337
   macro avg       0.87      0.87      0.87       337
weighted avg       0.88      0.88      0.88       337



#**PART 2**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/trein 1-3-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/2/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix/VGG19_fine-tuning_avg_4_classes_mix_data_part1345.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 337 images belonging to 4 classes.


In [ ]:
ac2v = model.evaluate(valid_image_gen)
ac2v

11/11 [==============================] - 240s 24s/step - loss: 0.7093 - accuracy: 0.8576


[0.7092862129211426, 0.857566773891449]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 3s 242ms/step


In [ ]:
classes2v = valid_image_gen.classes
#classes1v

In [ ]:
pred2v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[85,  5,  3,  2],
       [ 2, 36,  8,  6],
       [ 5,  1, 87,  2],
       [ 6,  5,  3, 81]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.87      0.89      0.88        95
           1       0.77      0.69      0.73        52
           2       0.86      0.92      0.89        95
           3       0.89      0.85      0.87        95

    accuracy                           0.86       337
   macro avg       0.85      0.84      0.84       337
weighted avg       0.86      0.86      0.86       337



#**PART 3**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/trein 1-2-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/3/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix/VGG19_fine-tuning_avg_4_classes_mix_data_part1245.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 337 images belonging to 4 classes.


In [ ]:
ac3v = model.evaluate(valid_image_gen)
ac3v

11/11 [==============================] - 233s 23s/step - loss: 0.7358 - accuracy: 0.8457


[0.7358007431030273, 0.8456973433494568]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 2s 213ms/step


In [ ]:
classes3v = valid_image_gen.classes
#classes1v

In [ ]:
pred3v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[84,  2,  7,  2],
       [ 4, 39,  4,  5],
       [ 5,  6, 81,  3],
       [ 0,  9,  5, 81]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.90      0.88      0.89        95
           1       0.70      0.75      0.72        52
           2       0.84      0.85      0.84        95
           3       0.89      0.85      0.87        95

    accuracy                           0.85       337
   macro avg       0.83      0.83      0.83       337
weighted avg       0.85      0.85      0.85       337



#**PART 4**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/trein 1-2-3-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/4/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix/VGG19_fine-tuning_avg_4_classes_mix_data_part1235.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 337 images belonging to 4 classes.


In [ ]:
ac4v = model.evaluate(valid_image_gen)
ac4v

11/11 [==============================] - 233s 23s/step - loss: 0.7680 - accuracy: 0.8398


[0.7680484056472778, 0.8397626280784607]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 2s 214ms/step


In [ ]:
classes4v = valid_image_gen.classes
#classes1v

In [ ]:
pred4v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[88,  2,  3,  2],
       [ 5, 36,  1, 10],
       [ 7,  3, 77,  8],
       [ 5,  6,  2, 82]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.84      0.93      0.88        95
           1       0.77      0.69      0.73        52
           2       0.93      0.81      0.87        95
           3       0.80      0.86      0.83        95

    accuracy                           0.84       337
   macro avg       0.83      0.82      0.83       337
weighted avg       0.84      0.84      0.84       337



#**PART 5**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/trein 1-2-3-4/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data/5/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix/VGG19_fine-tuning_avg_4_classes_mix_data_part1234.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 339 images belonging to 4 classes.


In [ ]:
ac5v = model.evaluate(valid_image_gen)
ac5v

11/11 [==============================] - 234s 23s/step - loss: 0.6109 - accuracy: 0.8525


[0.6108812689781189, 0.8525073528289795]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 2s 217ms/step


In [ ]:
classes5v = valid_image_gen.classes
#classes1v

In [ ]:
pred5v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[86,  3,  4,  2],
       [ 5, 38,  7,  4],
       [ 2,  5, 84,  4],
       [ 3,  8,  3, 81]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.90      0.91      0.90        95
           1       0.70      0.70      0.70        54
           2       0.86      0.88      0.87        95
           3       0.89      0.85      0.87        95

    accuracy                           0.85       339
   macro avg       0.84      0.84      0.84       339
weighted avg       0.85      0.85      0.85       339



#**Calculations**

VALIDATION

In [ ]:
acv_media = np.mean([ac1v[1],ac2v[1],ac3v[1],ac4v[1],ac5v[1]])
acv_media

0.8541810035705566

In [ ]:
todas_classesv = np.concatenate((classes1v,classes2v,classes3v,classes4v,classes5v),axis=0)

In [ ]:
todas_predv = np.concatenate((pred1v,pred2v,pred3v,pred4v,pred5v),axis=0)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

*   0: covid
*   1: dip
*   2: normais
*   3: tuberculose



In [ ]:
confusion_matrix(todas_classesv,todas_predv)

array([[428,  16,  18,  13],
       [ 19, 191,  26,  26],
       [ 23,  16, 413,  23],
       [ 16,  34,  16, 409]])

In [ ]:
print(classification_report(todas_classesv,todas_predv))

              precision    recall  f1-score   support

           0       0.88      0.90      0.89       475
           1       0.74      0.73      0.74       262
           2       0.87      0.87      0.87       475
           3       0.87      0.86      0.86       475

    accuracy                           0.85      1687
   macro avg       0.84      0.84      0.84      1687
weighted avg       0.85      0.85      0.85      1687



*   0: covid
*   1: dip
*   2: normais
*   3: tuberculose

