In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.image import imread
import tensorflow as tf
import pandas as pd
import random
import cv2
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Select the Runtime > "Change runtime type" menu to enable a GPU accelerator, ')
  print('and then re-execute this cell.')
else:
  print(gpu_info)

Fri Nov 17 22:36:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
image_shape = (224,224,3)
batch_size = 32

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
image_gen = ImageDataGenerator()

In [ ]:
from keras.models import load_model

In [ ]:
def int_predict (pred_probabilities):
  predictions = np.zeros((pred_probabilities.shape[0],1),dtype=int)
  i = 0
  while i < pred_probabilities.shape[0]:
    predictions[i,:] = [np.argmax(pred_probabilities[i])]
    i = i + 1

  return predictions

In [ ]:
test_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/RXT teste mix_data/'

#**PART 1**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/trein 2-3-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/1/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_mix_data_part2345.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 337 images belonging to 4 classes.


In [ ]:
ac1v = model.evaluate(valid_image_gen)
ac1v

11/11 [==============================] - 58s 5s/step - loss: 0.7692 - accuracy: 0.8783


[0.7692239880561829, 0.8783382773399353]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 2s 182ms/step


In [ ]:
classes1v = valid_image_gen.classes
#classes1v

In [ ]:
pred1v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[87,  2,  6,  0],
       [ 4, 42,  2,  4],
       [ 4,  2, 85,  4],
       [ 4,  5,  4, 82]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.88      0.92      0.90        95
           1       0.82      0.81      0.82        52
           2       0.88      0.89      0.89        95
           3       0.91      0.86      0.89        95

    accuracy                           0.88       337
   macro avg       0.87      0.87      0.87       337
weighted avg       0.88      0.88      0.88       337



#**PART 2**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/trein 1-3-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/2/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_mix_data_part1345.h5')

VALIDATION

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 337 images belonging to 4 classes.


In [ ]:
ac2v = model.evaluate(valid_image_gen)
ac2v

11/11 [==============================] - 54s 5s/step - loss: 0.9214 - accuracy: 0.8635


[0.9213711619377136, 0.8635014891624451]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 3s 212ms/step


In [ ]:
classes2v = valid_image_gen.classes
#classes1v

In [ ]:
pred2v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[90,  4,  1,  0],
       [ 6, 37,  3,  6],
       [ 5,  4, 82,  4],
       [ 3,  8,  2, 82]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.87      0.95      0.90        95
           1       0.70      0.71      0.70        52
           2       0.93      0.86      0.90        95
           3       0.89      0.86      0.88        95

    accuracy                           0.86       337
   macro avg       0.85      0.85      0.85       337
weighted avg       0.87      0.86      0.86       337



#**PART 3**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/trein 1-2-4-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/3/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_mix_data_part1245.h5')

VALIDAÇÃO

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 337 images belonging to 4 classes.


In [ ]:
ac3v = model.evaluate(valid_image_gen)
ac3v

11/11 [==============================] - 54s 5s/step - loss: 0.7500 - accuracy: 0.8516


[0.7500306367874146, 0.8516320586204529]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 3s 230ms/step


In [ ]:
classes3v = valid_image_gen.classes
#classes1v

In [ ]:
pred3v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[87,  3,  3,  2],
       [ 4, 33, 12,  3],
       [ 6,  1, 87,  1],
       [ 3,  6,  6, 80]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.87      0.92      0.89        95
           1       0.77      0.63      0.69        52
           2       0.81      0.92      0.86        95
           3       0.93      0.84      0.88        95

    accuracy                           0.85       337
   macro avg       0.84      0.83      0.83       337
weighted avg       0.85      0.85      0.85       337



#**PART 4**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/trein 1-2-3-5/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/4/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_mix_data_part1235.h5')

VALIDAÇÃO

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 337 images belonging to 4 classes.


In [ ]:
ac4v = model.evaluate(valid_image_gen)
ac4v

11/11 [==============================] - 53s 5s/step - loss: 0.7975 - accuracy: 0.8694


[0.7975200414657593, 0.8694362044334412]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 2s 199ms/step


In [ ]:
classes4v = valid_image_gen.classes
#classes1v

In [ ]:
pred4v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[81,  4,  4,  6],
       [ 2, 41,  5,  4],
       [ 4,  1, 88,  2],
       [ 3,  6,  3, 83]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.90      0.85      0.88        95
           1       0.79      0.79      0.79        52
           2       0.88      0.93      0.90        95
           3       0.87      0.87      0.87        95

    accuracy                           0.87       337
   macro avg       0.86      0.86      0.86       337
weighted avg       0.87      0.87      0.87       337



#**PART 5**

In [ ]:
data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/trein 1-2-3-4/'
valid_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/KFolds mix_data aumentado/5/'

In [ ]:
model = tf.keras.models.load_model('/content/drive/My Drive/Colab Notebooks/Mestrado final/Novos treinamentos/KFolds mix aumentado/VGG19_fine-tuning_RandAugm_avg_4_classes_mix_data_part1234.h5')

In [ ]:
valid_image_gen = image_gen.flow_from_directory(valid_dir,
                                               #target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='categorical',
                                               shuffle=False)

Found 339 images belonging to 4 classes.


In [ ]:
ac5v = model.evaluate(valid_image_gen)
ac5v

11/11 [==============================] - 57s 6s/step - loss: 0.9062 - accuracy: 0.8496


[0.9062471985816956, 0.8495575189590454]

In [ ]:
pred_probabilities = model.predict(valid_image_gen)

11/11 [==============================] - 2s 188ms/step


In [ ]:
classes5v = valid_image_gen.classes
#classes1v

In [ ]:
pred5v = predictions = int_predict(pred_probabilities)
#pred1v

In [ ]:
valid_image_gen.class_indices

{'covid': 0, 'dip': 1, 'normais': 2, 'tuberculose': 3}

In [ ]:
confusion_matrix(valid_image_gen.classes,predictions)

array([[79,  3, 11,  2],
       [ 4, 42,  5,  3],
       [ 4,  2, 84,  5],
       [ 4,  6,  2, 83]])

In [ ]:
print(classification_report(valid_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85        95
           1       0.79      0.78      0.79        54
           2       0.82      0.88      0.85        95
           3       0.89      0.87      0.88        95

    accuracy                           0.85       339
   macro avg       0.84      0.84      0.84       339
weighted avg       0.85      0.85      0.85       339



#**Calculations**

In [ ]:
acv_media = np.mean([ac1v[1],ac2v[1],ac3v[1],ac4v[1],ac5v[1]])
acv_media

0.8624931097030639

In [ ]:
todas_classesv = np.concatenate((classes1v,classes2v,classes3v,classes4v,classes5v),axis=0)

In [ ]:
todas_predv = np.concatenate((pred1v,pred2v,pred3v,pred4v,pred5v),axis=0)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

*   0: covid
*   1: dip
*   2: normais
*   3: tuberculose



In [ ]:
confusion_matrix(todas_classesv,todas_predv)

array([[424,  16,  25,  10],
       [ 20, 195,  27,  20],
       [ 23,  10, 426,  16],
       [ 17,  31,  17, 410]])

In [ ]:
print(classification_report(todas_classesv,todas_predv))

              precision    recall  f1-score   support

           0       0.88      0.89      0.88       475
           1       0.77      0.74      0.76       262
           2       0.86      0.90      0.88       475
           3       0.90      0.86      0.88       475

    accuracy                           0.86      1687
   macro avg       0.85      0.85      0.85      1687
weighted avg       0.86      0.86      0.86      1687



*   0: covid
*   1: dip
*   2: normais
*   3: tuberculose

